language: node_js
node_js:
  - "6"
  - "8"
  - "10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email: false

script:
  - npm run test:ci

after_success:
  - npm run report-coverage
